<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.openhab.addons.bundles</groupId>
    <artifactId>org.openhab.addons.reactor.bundles</artifactId>
    <version>5.2.0-SNAPSHOT</version>
  </parent>

  <artifactId>org.openhab.binding.icomfortwifi</artifactId>
  <packaging>bundle</packaging>
  <name>openHAB Add-ons :: Bundles :: iComfort WiFi Binding</name>

  <properties>
    <!-- Disable Karaf feature verification -->
    <skip.karaf.feature.verification>true</skip.karaf.feature.verification>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.openhab.core.bundles</groupId>
      <artifactId>org.openhab.core</artifactId>
      <version>${project.version}</version>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>org.openhab.core.bundles</groupId>
      <artifactId>org.openhab.core.thing</artifactId>
      <version>${project.version}</version>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>org.eclipse.jdt</groupId>
      <artifactId>org.eclipse.jdt.annotation</artifactId>
      <version>2.2.700</version>
      <scope>compile</scope>
    </dependency>

    <dependency>
      <groupId>org.openhab.core.bundles</groupId>
      <artifactId>org.openhab.core.io.net</artifactId>
      <version>${project.version}</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>

  <repositories>
    <repository>
      <id>openhab-release</id>
      <url>https://openhab.jfrog.io/openhab/libs-release</url>
    </repository>

    <repository>
      <releases>
        <enabled>false</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
      <id>openhab-snapshot</id>
      <url>https://openhab.jfrog.io/openhab/libs-snapshot</url>
    </repository>
  </repositories>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.karaf.tooling</groupId>
        <artifactId>karaf-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>karaf-feature-verification</id>
            <goals>
              <goal>verify</goal>
            </goals>
            <phase>verify</phase>
            <configuration>
              <skip>${skip.karaf.feature.verification}</skip>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
